name: Deploy to AWS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install Backend Dependencies
        run: |
          cd elearning-backend
          npm install

      - name: Build Backend
        run: |
          cd elearning-backend
          npm run build --if-present

      - name: Install Frontend Dependencies
        run: |
          cd elearning-frontend
          npm install

      - name: Build Frontend
        run: |
          cd elearning-frontend
          npm run build --if-present

      - name: Prepare Deployment Package
        run: |
          mkdir -p deployment
          cp -r elearning-backend deployment/
          cp -r elearning-frontend/build deployment/frontend
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Deploy to S3 (Frontend)
        run: |
          aws s3 sync deployment/frontend s3://elearning-cclab/ --delete

      - name: Create backend ZIP for Elastic Beanstalk
        run: |
          cd deployment
          zip -r ../backend.zip elearning-backend
      
      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name ElearningApp \
            --version-label "ver-${{ github.sha }}" \
            --source-bundle S3Bucket="elasticbeanstalk-ap-south-1-124355639294",S3Key="backend.zip"
          
          aws elasticbeanstalk update-environment \
            --application-name ElearningApp \
            --environment-name ElearningApp-env \
            --version-label "ver-${{ github.sha }}"